line=input("enter the line:")
print("before going to remove all spaces:")
print(f"the length of string is{len(line)}")
line=line.strip()
print("after removing spaces:")
print(f"length of string is={len(line)}")
pos=line.find("bldea")
if(pos>=-1):
    print(f"blde word is found at the position:{pos}")
    line=line.replace("bldea","kle")
    print(line)
    line=line.upper()
    print(line)
    line=line.title()
    print(line)